name: "Build and Push AMD64 Docker Images"

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG_PREFIX: ""
  BASE_IMAGE: ghcr.io/m1k1o/neko/base:latest
  PLATFORMS: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        tag: [plex] # Add more tags here if necessary

    env:
      TAG_NAME: ${{ matrix.tag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Install Snapcraft and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo systemctl start snapd
          sudo snap install snapcraft --classic
          sudo snap install plex-desktop # Install the required Snap app

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.TAG_PREFIX }}${{ env.TAG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Set to the Docker build context (current directory or Dockerfile location)
          file: ./Dockerfile # Path to Dockerfile, change if necessary
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
